# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # config.vm.box = "http://yum.oracle.com/boxes/oraclelinux/ol73/ol73.box"
  config.vm.box = "oraclelinux/ol73"
  config.vm.box_url = "http://yum.oracle.com/boxes/oraclelinux/ol73/ol73.box"
  config.vm.box_check_update = false

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  else
    puts "vagrant-cachier plugin not installed"
  end

  if Vagrant.has_plugin?('vagrant-timezone')
    config.timezone.value = "America/New_York"
  else
    puts "vagrant-timezone plugin not installed"
  end

  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = "oracle12c-vagrant"
  end

  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 5500, host: 5500

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "ORACLE_BASE"         => "/opt/oracle",
       "ORACLE_HOME"         => "/opt/oracle/product/12.2.0.1/dbhome_1",
       "ORACLE_SID"          => "ORCLCDB",
       "ORACLE_PDB"          => "ORCLPDB1",
       "ORACLE_CHARACTERSET" => "AL32UTF8"
    }

end
